services:
  web:
    build:
      context: .
      target: develop
    container_name: udemy-fastapi-container
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - venv-data:/app/.venv

    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/

        - action: rebuild
          path: ./uv.lock
volumes:
  venv-data:
