[project]
name = "udemy-fastapi"
version = "0.1.0"
description = "udemy fastapi tutorial"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "streamlit>=1.45.1",
    "uvicorn>=0.34.2",
]

[dependency-groups]
dev = [
    "fastapi-cli>=0.0.7",
    "ruff>=0.11.8",
]

